<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="LinkUI" Id="{1a1c3c5e-22cb-45b4-b980-f09563072448}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM LinkUI
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[






//==================Pause button from UI================================
GVL_SignalHanlding.fbPauseUI.bSignalInput := GVL_General.bPauseBtnUI;
GVL_SignalHanlding.fbPauseUI.SignalEnable(bSignalLocalEnable:= TRUE);
GVL_SignalHanlding.fbPauseUI.SetOutput();
//==================Pause button from UI================================








]]></ST>
    </Implementation>
    <LineIds Name="LinkUI">
      <LineId Id="47" Count="5" />
      <LineId Id="41" Count="1" />
      <LineId Id="15" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>