<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="MAIN" Id="{3842b7b5-2d54-412a-975a-36a7ea8a0c51}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	SignalHandler();
	
//======================Handl the signal from UI=================== 
	LinkUI();
//======================Handl the signal from UI=================== 



//======================Handl the signal from Hardware===================
	LinkHWIO();
//======================Handl the signal from Hardware===================




//====================handle the lights rolling======================
	LampControl();
//====================handle the lights rolling======================

//=========Machine mode selecion================
	ModeManger();
//=========Machine mode selecion================





					
					]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="41" Count="1" />
      <LineId Id="52" Count="0" />
      <LineId Id="40" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="43" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="58" Count="0" />
      <LineId Id="57" Count="0" />
      <LineId Id="47" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="60" Count="1" />
      <LineId Id="59" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="65" Count="5" />
      <LineId Id="64" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="24" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>