<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="SignalHandler" Id="{8d1c351c-c5f8-4138-91c0-bf23a590a776}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SignalHandler
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SignalHandler">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>