<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="LampControl" Id="{db76b55e-6d95-4fc8-8f68-3af01c71506b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LampControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="LampControl">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>